import argparse
import json
import numpy as np
import sys
import os
import trimesh
import math

def parse_args():
    parser = argparse.ArgumentParser(description="Apply transformations to a mesh, with inverse scaling applied FIRST, followed by manual rotation correction (selectable Euler order) and the rest of the inverse transform.")
    parser.add_argument("--mesh_in", required=True, help="Path to the input mesh file (e.g., mesh.obj, mesh.ply).")
    parser.add_argument("--mesh_out", required=True, help="Path to save the transformed output mesh file.")
    parser.add_argument("--meta_path", default="transform_meta.json", help="Path to the transform_meta.json file generated by colmap2nerf.py.")
    parser.add_argument("--rotate_x_deg", type=float, default=90.0, help="Additional rotation around the X axis in degrees.")
    parser.add_argument("--rotate_y_deg", type=float, default=0.0, help="Additional rotation around the Y axis in degrees.")
    parser.add_argument("--rotate_z_deg", type=float, default=-0.0, help="Additional rotation around the Z axis in degrees.")
    parser.add_argument("--euler_order", type=str, default='XYZ', choices=['XYZ', 'YZX', 'ZXY', 'XZY', 'YXZ', 'ZYX'], help="Order of Euler angles for manual rotation correction.")
    parser.add_argument("--mirror_yz", action="store_true", help="Apply mirroring across the YZ plane after the rest of the inverse transform.")
    parser.add_argument("--translate_x", type=float, default=0.0, help="Additional translation along the X axis.")
    parser.add_argument("--translate_y", type=float, default=0.0, help="Additional translation along the Y axis.")
    parser.add_argument("--translate_z", type=float, default=0.0, help="Additional translation along the Z axis.")
    return parser.parse_args()

def rotation_matrix_x(theta_deg):
    """Generates a 3x3 rotation matrix around the X axis (in degrees)."""
    theta_rad = math.radians(theta_deg)
    c, s = np.cos(theta_rad), np.sin(theta_rad)
    return np.array([
        [1, 0, 0],
        [0, c, -s],
        [0, s, c]
    ], dtype=np.float64)

def rotation_matrix_y(theta_deg):
    """Generates a 3x3 rotation matrix around the Y axis (in degrees)."""
    theta_rad = math.radians(theta_deg)
    c, s = np.cos(theta_rad), np.sin(theta_rad)
    return np.array([
        [c, 0, s],
        [0, 1, 0],
        [-s, 0, c]
    ], dtype=np.float64)

def rotation_matrix_z(theta_deg):
    """Generates a 3x3 rotation matrix around the Z axis (in degrees)."""
    theta_rad = math.radians(theta_deg)
    c, s = np.cos(theta_rad), np.sin(theta_rad)
    return np.array([
        [c, -s, 0],
        [s, c, 0],
        [0, 0, 1]
    ], dtype=np.float64)

def combine_euler_rotations(rx_deg, ry_deg, rz_deg, order='XYZ'):
    """Combines rotations around X, Y, Z axes in a specified Euler order."""
    Rx = rotation_matrix_x(rx_deg)
    Ry = rotation_matrix_y(ry_deg)
    Rz = rotation_matrix_z(rz_deg)

    if order == 'XYZ':
        return Rz @ Ry @ Rx
    elif order == 'XZY':
        return Ry @ Rz @ Rx
    elif order == 'YXZ':
        return Rz @ Rx @ Ry
    elif order == 'YZX':
        return Rx @ Rz @ Ry
    elif order == 'ZXY':
        return Ry @ Rx @ Rz
    elif order == 'ZYX':
        return Rx @ Ry @ Rz
    else:
        raise ValueError(f"Unsupported Euler order: {order}")


def mirroring_matrix_yz():
    """Generates a 4x4 mirroring matrix across the YZ plane (negates X)."""
    return np.array([
        [-1, 0, 0, 0],
        [ 0, 1, 0, 0],
        [ 0, 0, 1, 0],
        [ 0, 0, 0, 1]
    ], dtype=np.float64)

def translation_matrix(tx, ty, tz):
    """Generates a 4x4 translation matrix."""
    return np.array([
        [1, 0, 0, tx],
        [0, 1, 0, ty],
        [0, 0, 1, tz],
        [0, 0, 0, 1]
    ], dtype=np.float64)

def scaling_matrix(s):
    """Generates a 4x4 uniform scaling matrix."""
    return np.array([
        [s, 0, 0, 0],
        [0, s, 0, 0],
        [0, 0, s, 0],
        [0, 0, 0, 1]
    ], dtype=np.float64)


def main():
    args = parse_args()

    if not os.path.exists(args.meta_path):
        print(f"Error: transform_meta.json not found at {args.meta_path}")
        sys.exit(1)

    try:
        with open(args.meta_path, "r") as f:
            meta = json.load(f)
            rotation_up_4x4 = np.array(meta["rotation_up"], dtype=np.float64)
            center_of_attention = np.array(meta["center_of_attention"], dtype=np.float64)
            avglen = float(meta["avglen"])
    except (FileNotFoundError, json.JSONDecodeError, KeyError, ValueError) as e:
        print(f"Error loading or parsing transform_meta.json: {e}")
        sys.exit(1)

    rotation_up_3x3 = rotation_up_4x4[0:3, 0:3]

    print(f"Loaded transformation metadata from {args.meta_path}")
    print(f"  rotation_up (extracted 3x3):\n{rotation_up_3x3}")
    print(f"  center_of_attention: {center_of_attention}")
    print(f"  avglen: {avglen}")

    scale_factor = 4.0 / avglen
    inv_scale_factor = 1.0 / scale_factor
    print(f"  scale_factor: {scale_factor}")
    print(f"  inv_scale_factor: {inv_scale_factor}")

    R_up_T_3x3 = rotation_up_3x3.T

    M_intermediate_to_colmap_3x3 = np.array([
        [0, 1, 0],
        [1, 0, 0],
        [0, 0, -1]
    ], dtype=np.float64)
    print("\nDerived intermediate to COLMAP axis transformation matrix:\n", M_intermediate_to_colmap_3x3)

    T_nerf_to_colmap_no_scale = np.eye(4, dtype=np.float64)
    rot_part_3x3 = M_intermediate_to_colmap_3x3 @ R_up_T_3x3
    translate_part_3d = M_intermediate_to_colmap_3x3 @ R_up_T_3x3 @ center_of_attention

    T_nerf_to_colmap_no_scale[0:3, 0:3] = rot_part_3x3
    T_nerf_to_colmap_no_scale[0:3, 3] = translate_part_3d

    print("\nCalculated inverse transformation matrix (NeRF -> COLMAP) without scaling:\n", T_nerf_to_colmap_no_scale)


    T_rotation_correction = np.eye(4, dtype=np.float64)
    if args.rotate_x_deg != 0.0 or args.rotate_y_deg != 0.0 or args.rotate_z_deg != 0.0:
        R_correction_3x3 = combine_euler_rotations(args.rotate_x_deg, args.rotate_y_deg, args.rotate_z_deg, order=args.euler_order)
        T_rotation_correction[0:3, 0:3] = R_correction_3x3
        print(f"\nConstructed manual rotation correction matrix ({args.euler_order} Euler): {args.rotate_x_deg} deg around X, {args.rotate_y_deg} deg around Y, {args.rotate_z_deg} deg around Z.")
        print("Correction rotation matrix:\n", R_correction_3x3)


    T_mirror_yz = np.eye(4, dtype=np.float64)
    if args.mirror_yz:
        T_mirror_yz = mirroring_matrix_yz()
        print("\nConstructed mirroring matrix across YZ plane.")
        print("Mirroring matrix YZ:\n", T_mirror_yz)

    T_translation_correction = np.eye(4, dtype=np.float64)
    if args.translate_x != 0.0 or args.translate_y != 0.0 or args.translate_z != 0.0:
        T_translation_correction = translation_matrix(args.translate_x, args.translate_y, args.translate_z)
        print(f"\nConstructed manual translation correction matrix: ({args.translate_x}, {args.translate_y}, {args.translate_z}).")
        print("Translation matrix:\n", T_translation_correction)

    T_inverse_scaling = scaling_matrix(inv_scale_factor)
    print("\nConstructed inverse scaling matrix:\n", T_inverse_scaling)


    T_total_inv = T_translation_correction @ T_mirror_yz @ T_nerf_to_colmap_no_scale @ T_rotation_correction @ T_inverse_scaling

    print("\nCalculated total inverse transformation matrix (NeRF -> COLMAP) with corrections:\n", T_total_inv)

    try:
        mesh = trimesh.load_mesh(args.mesh_in)
        if not isinstance(mesh, trimesh.Trimesh):
             print(f"Error: Loaded object is not a Trimesh (type: {type(mesh).__name__}). Exiting.")
             sys.exit(1)
        print(f"\nLoaded mesh from {args.mesh_in} with {len(mesh.vertices)} vertices and {len(mesh.faces) if hasattr(mesh, 'faces') else 0} faces.")

    except Exception as e:
        print(f"Error loading mesh file {args.mesh_in}: {e}")
        print("Please ensure the file exists and is in a format supported by trimesh (e.g., obj, ply, stl).")
        sys.exit(1)


    vertices_nerf = mesh.vertices.copy() 


    vertices_nerf_hom = np.hstack([vertices_nerf, np.ones((vertices_nerf.shape[0], 1), dtype=np.float64)])
    vertices_colmap_hom = vertices_nerf_hom @ T_total_inv.T
    vertices_colmap = vertices_colmap_hom[:, :3]
    mesh.vertices = vertices_colmap
    print(f"Transformed {len(vertices_nerf)} vertices.")

    try:
        mesh.export(args.mesh_out)
        print(f"Transformed mesh saved to {args.mesh_out}")
    except Exception as e:
        print(f"Error saving mesh file {args.mesh_out}: {e}")
        print("Please ensure the output path is valid and trimesh supports the output format.")
        sys.exit(1)

if __name__ == "__main__":
    main()
